version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: MRV-shelfmark_server_1
      APP_PORT: 8084
    
  server:
    image: ghcr.io/calibrain/shelfmark:latest
    user: "1000:1000"
    init: true

  shelfmark:
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - /path/to/books:/books # Default destination for book downloads
      - /path/to/config:/config # App configuration
      # Required for torrent / usenet - path must match your download client's volume exactly
      # - /path/to/downloads:/path/to/downloads
